apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io #{{ include "custom-metrics-api.fullname" . }}
spec:
  insecureSkipTLSVerify: true
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 5
  service:
    name: {{ include "custom-metrics-api.fullname" . }}
    namespace: custom-metrics-api
  version: v1beta1